
name: Maven Package

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v2
	
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'

    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: SonarQube Scanner
      uses: sonarsource/sonarqube-scan-action@master
      env:
        # SonarQube server URL
        SONAR_HOST_URL: http://35.172.192.145:9000
        # Login or authentication token of a SonarQube user
        SONAR_TOKEN: ${{ secrets.SONARQUBE_TOKEN }}
